#!/usr/bin/env python3
"""Regenerates Localization/*.lproj/Localizable.strings from the keys found in the sources.

English uses the key itself; German comes from scripts/de_translations.py.
Run after changing UI text, then fill in any German text it reports as missing.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from check_strings import ROOT, source_keys  # noqa: E402
from de_translations import DE  # noqa: E402


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write(lang: str, mapping: dict[str, str]) -> None:
    path = ROOT / f"Localization/{lang}.lproj/Localizable.strings"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by scripts/gen_strings.py */", ""]
    lines += [f'"{escape(k)}" = "{escape(v)}";' for k, v in sorted(mapping.items())]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


keys = source_keys()
missing = sorted(k for k in keys if k not in DE)
write("en", {k: k for k in keys})
write("de", {k: DE.get(k, k) for k in keys})
if missing:
    print("Missing German text for:")
    for k in missing:
        print(f"  {k}")
    sys.exit(1)
print(f"Wrote {len(keys)} strings.")
